FROM python:3.12-slim

WORKDIR /app

COPY requirements-base.txt .
RUN pip install --no-cache-dir --default-timeout=300 --retries=10 -r requirements-base.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "connector.main:app", "--host", "0.0.0.0", "--port", "8000"]
